#ifndef SELENA_LEXER_ERRORS_H_
#define SELENA_LEXER_ERRORS_H_

#include <stdio.h>
#include <stdint.h>

typedef enum {
    SLN_LEX_OK,
    SLN_LEX_NO_FILE,
    SLN_LEX_NO_ERROR_STREAM,
    SLN_LEX_NO_TOKEN_BUFFER,
    SLN_LEX_INVALID_TOKEN,
    SLN_LEX_UNTERMINATED_STRING,
    SLN_LEX_UNTERMINATED_CHAR,
    SLN_LEX_INVALID_ESCAPE_SEQUENCE,
    SLN_LEX_ALLOCATION_FAILED,
} sln_lex_error_t;

#endif // SELENA_LEXER_ERRORS_H_