
/**
 * @brief Autogenerated messages, warnings and errors.
 * @author 
 */

#ifndef SELENA_MSG_RESOURCES_H_
#define SELENA_MSG_RESOURCES_H_

typedef enum {
    SLN_MSG_NO_ARGS,
} sln_msg_t;

#endif // SELENA_MSG_RESOURCES_H_