
/**
 * @brief Autogenerated file of error/warnings and message texts.
 * @author 
 * @date
 */

#ifndef SELENA_MSG_RESOURCE_H_
#define SELENA_MSG_RESOURCE_H_

#define _SLN_MSG_START_POS 4 // 0b100

typedef enum {
    SLN_MSG_INIT_INFO,
    SLN_MSG_INIT_WARN,
    SLN_MSG_INIT_ERRR,
    
    SLN_MSG_NO_ARGS,

    // others
    _SLN_MSG_COUNT,
} sln_res_msg_t;

const char* sln_res_msg_get(sln_res_msg_t msg_code);

#endif // SELENA_MSG_RESOURCE_H_